name: securebank

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: ${DB_USER:-securebank}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?copie .env.example para .env e defina DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT:-5439}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-securebank} -d securebank"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:?defina REDIS_PASSWORD no .env}", "--save", "", "--appendonly", "no"]
    ports:
      - "127.0.0.1:${REDIS_PORT:-6380}:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" --no-auth-warning ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  securebank-api:
    build: ./securebank-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/securebank
      DB_USER: ${DB_USER:-securebank}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MFA_ENCRYPTION_KEY: ${MFA_ENCRYPTION_KEY:?defina MFA_ENCRYPTION_KEY no .env}
      BOOTSTRAP_ADMIN_EMAIL: ${BOOTSTRAP_ADMIN_EMAIL:-}
      BOOTSTRAP_ADMIN_PASSWORD: ${BOOTSTRAP_ADMIN_PASSWORD:-}
      API_DOCS_ENABLED: "true"
    ports:
      - "127.0.0.1:${API_PORT:-8100}:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/api/v1/actuator/health/readiness"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s

  securebank-web:
    build: ./securebank-web
    depends_on:
      securebank-api:
        condition: service_healthy
    ports:
      - "${WEB_PORT:-3500}:8080"

volumes:
  pgdata:
