apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        # clicar no traceId de uma linha de log abre o trace no Jaeger
        - name: traceId
          matcherType: label
          matcherRegex: trace_id
          url: '$${__value.raw}'
          datasourceUid: jaeger
  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger:16686
