package com.securebank.audit.domain;

/** Eventos de segurança e de operações críticas que viram trilha de auditoria (seção 25). */
public enum AuditEvent {
    USER_REGISTERED, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, SESSION_REVOKED, REFRESH_TOKEN_REUSE_DETECTED,
    PASSWORD_CHANGED, MFA_ENABLED, MFA_DISABLED, MFA_FAILED,
    TRANSFER_CREATED, TRANSFER_FAILED, PAYMENT_CREATED, PAYMENT_FAILED,
    ACCOUNT_BLOCKED, ACCOUNT_UNBLOCKED, LIMIT_CHANGED,
    PIX_KEY_CREATED, PIX_KEY_DELETED, PIX_SENT, PIX_FAILED,
    PIGGY_CREATED, PIGGY_DEPOSIT, PIGGY_WITHDRAW, PIGGY_CLOSED,
    USER_CREATED, USER_DISABLED, USER_ENABLED, ACCESS_DENIED
}
